apiVersion: v1
kind: Service
metadata:
  namespace: strategy
  name: print-version
  labels:
    app: print-version
spec:
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: print-version

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: strategy
  name: print-version
  labels:
    app: print-version
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 0
  selector:
    matchLabels:
      app: print-version
  template:
    metadata:
      labels:
        app: print-version
    spec:
      containers:
        - name: print-version
          image: ghcr.io/gihyodocker/print-version:v0.0.1
          ports:
            - containerPort: 8080
          startupProbe:
            exec:
              command: ["sh", "-c", "echo 'startup probe'"]
          livenessProbe:
            exec:
              command: ["cat", "/var/tmp/live.txt"]
            periodSeconds: 5
          readinessProbe:
            httpGet:
              port: 8080
              path: /hc
            timeoutSeconds: 3
            periodSeconds: 5
