replicaCount: 1

imagePullSecrets: []
# This is to override the chart name.
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false

nginx:
  image:
    repository: ghcr.io/gihyodocker/simple-nginx-proxy
    tag: v0.1.0
    pullPolicy: IfNotPresent
  port: 80
  serverName: localhost
  backendHost: localhost:8080
  maxFails: 3
  failTimeout: 10s
  livenessProbe:
    httpGet:
      path: /
      port: http
  readinessProbe:
    httpGet:
      path: /
      port: http

echo:
  image:
    repository: ghcr.io/gihyodocker/echo
    tag: v0.1.0
    pullPolicy: IfNotPresent
  port: 8080

podAnnotations: {}

podLabels: {}

podSecurityContext:
  {}
  # fsGroup: 2000

securityContext:
  {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false

gateway:
  gatewayClassName: eg
  port: 80

httpRoute:
  # HTTPRoute enabled.
  enabled: true
  # HTTPRoute annotations.
  annotations: {}
  # Which Gateways this Route is attached to.
  parentRefs:
    - name: gateway
  # Hostnames matching HTTP header.
  hostnames:
    - chart-example.local
  # List of rules and filters applied.
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
  #   filters:
  #   - type: RequestHeaderModifier
  #     requestHeaderModifier:
  #       set:
  #       - name: My-Overwrite-Header
  #         value: this-is-the-only-value
  #       remove:
  #       - User-Agent
  # - matches:
  #   - path:
  #       type: PathPrefix
  #       value: /echo
  #     headers:
  #     - name: version
  #       value: v2

resources:
  {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

# This section is for setting up autoscaling more information can be found here: https://kubernetes.io/docs/concepts/workloads/autoscaling/
autoscaling:
  enabled: false

nodeSelector: {}

tolerations: []

affinity: {}
