apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: echo-dev
resources:
  - ../../base
patches:
  - path: patch-deployment.yaml
  - path: patch-ingress.yaml
    target:
      kind: Ingress
      name: echo
  - target:
      kind: Namespace
      name: default
    patch: |-
      - op: replace
        path: /metadata/name
        value: echo-dev
configMapGenerator:
  - name: nginx-config
    literals:
      - SERVER_NAME=localhost
    options:
      disableNameSuffixHash: true
images:
  - name: nginx
    newName: ghcr.io/gihyodocker/simple-nginx-proxy
    newTag: v0.1.0
