apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: echo-dev
resources:
  - ../../base
patches:
  - path: patch-deployment.yaml
  - path: patch-gateway.yaml
    target:
      group: gateway.networking.k8s.io
      version: v1

configMapGenerator:
  - name: nginx-config
    literals:
      - SERVER_NAME=localhost
    options:
      disableNameSuffixHash: false # ハッシュ値を付与することで、ConfigMap 更新時にPodの再起動を促す

images:
  - name: nginx
    newName: ghcr.io/gihyodocker/simple-nginx-proxy
    newTag: v0.1.0
