apiVersion: v1
kind: Pod
metadata:
  name: pod-reader
  namespace: rbac
  labels:
    app: pod-reader
spec:
  serviceAccountName: pod-reader
  containers:
    - name: kubectl
      image: bitnami/kubectl:latest
      command: ["/bin/sh", "-c", "--"]
      args:
        - |
          while true; do
            echo "Listing pods in namespace 'rbac':"
            kubectl get pods -n rbac
            sleep 30
          done
      resources:
        requests:
          cpu: 100m
          memory: 100Mi
        limits:
          cpu: 100m
          memory: 100Mi
